package models

import groovy.json.JsonOutput
import groovy.transform.builder.Builder

import java.time.LocalDate

/**
 * Represents a Person entity using Builder pattern for flexibility.
 */
@Builder
class PersonModel {
    Long id // id generated by the "backend"
    Long personalCode
    String country
    String firstName
    String lastName
    String gender
    LocalDate dateOfBirth
    LocalDate dateOfDeath

    String toJson() {
        return JsonOutput.toJson([
                id          : id,
                personalCode: personalCode,
                country     : country,
                firstName   : firstName,
                lastName    : lastName,
                gender      : gender,
                dateOfBirth : dateOfBirth?.toString(),
                dateOfDeath : dateOfDeath?.toString()
        ])
    }
}
